# config/routes.rb
Rails.application.routes.draw do
  # Public landing page
  root 'home#index'

  # Authentication routes (simple, hand-rolled)
  get    'login',  to: 'sessions#new'     # login form
  post   'login',  to: 'sessions#create'  # create session
  delete 'logout', to: 'sessions#destroy' # end session

  # Dashboards
  get '/admin',    to: 'home#aindex'   # admin dashboard
  get '/userhome', to: 'home#uindex'   # standard user dashboard

  # Public search page
  get '/search', to: 'search#index'

  # CRUD resources generated by scaffold/generators
  resources :users
  resources :philosophers
  resources :categories
  resources :quotes
end
